### ISSUE TITLE
Download help

### ISSUE THREAD

**Issue by dylanxu054** [seemoo-lab/AirGuard#1]
**Hi there, This application is not available on google play and Releases has no content. Could you please provide the apk file to download and use?**

**Comment by Sn0wfreezeDev** [comment]
Hi, 

nice that you found our newest release. I'd really like to have it on Google Play, but Google refuses to let the app in. 
They claim that we are missing parts in our privacy policy, but we don't. So it's quite complicated at the moment. 

We wanted to release the source code and APKs here as well when we get it on Google Play.

**Comment by da-stoi** [comment]
Is there any chance AirGuard will be available on F-Droid?

**Comment by Sn0wfreezeDev** [comment]
Yes it will be available soon

**Comment by dylanxu054** [comment]
> Hi,
> 
> nice that you found our newest release. I'd really like to have it on Google Play, but Google refuses to let the app in.
> They claim that we are missing parts in our privacy policy, but we don't. So it's quite complicated at the moment.
> 
> We wanted to release the source code and APKs here as well when we get it on Google Play.

Thank you for your reply, I can’t wait to use this app, so I hope it will be available on google play soon.

**Comment by Trup3s** [comment]
@dylanxu054 @da-stoi 

We've just released a first version of the App! The FDroid release will happen soon<sup>TM</sup>. Google might take a bit longer, but we're working on it!
