### ISSUE TITLE
No notifications 

### ISSUE THREAD

**Issue by deathblade666** [seemoo-lab/AirGuard#12]
Hi I’ve version 1.0.4 installed and It found two air tags the other day but I never got a notification they were detected. Is there something I’m missing or do notifications trigger under certain situations?

I’m running it on a Pixel 2XL running CalyxOS (android 11). 

Please let me know if any  additional information would be helpful.

**Comment by Sn0wfreezeDev** [comment]
Hi @deathblade666, 

thank you for your report. We will look into this, but normally the tracking will only send a notification if you the same tag has been actually following you for about one hour. 
So this means that the app would have to find the same tag multiple times and that you have moved during that time. So if the tag is located in a backpack and you did not bring that backpack anywhere and just kept it at home the app won't send a notification. 

Also sometimes, AirTags do not switch into the tracking mode correctly. At the moment I'm not sure when this happens, but in that case they won't be detectable, but the *stalker* would not receive location updates in that case. 

Does this explain it or did the app misbehave and not send you a notification
