### ISSUE TITLE
(Question) devices in the background

### ISSUE THREAD

**Issue by Citro12** [seemoo-lab/AirGuard#123]
What do devices with a dark background mean compared to devices with a light background?
![Screenshot_2023-04-17-13-26-23-211_de seemoo at_tracking_detection release](https://user-images.githubusercontent.com/7021754/232471648-ae3c5292-c3a2-409e-b895-bde3357db7c6.jpg)

**Comment by Citro12** [comment]
![Screenshot_2023-04-05-00-12-21-284_de seemoo at_tracking_detection release](https://user-images.githubusercontent.com/7021754/229934233-633ab62c-6109-493f-8f27-97a8e39edc48.jpg)

**Comment by Sn0wfreezeDev** [comment]
Dark background is used for devices which are not in tracking mode
