### ISSUE TITLE
No notification/alert 

### ISSUE THREAD

**Issue by Simon442** [seemoo-lab/AirGuard#125]
I was on an event last week with few hundred people and while checking if app is working properly today, I found one AirTag was found. Luckily it just picked up AirTags someone had on that event but I did not receive any notifications or alerts on my device, which means it would also not notify me in a situation someone would actually try and track me. 

I have notifications enabled, battery optimisation disabled system wide and set unrestricted battery usage for AirGuard. 

Phone is Realme 7 Pro with custom ROM - Derpfest Android 13. 

![Screenshot_20230405-233423.png](https://user-images.githubusercontent.com/60188451/230217335-01dfc7f4-6b97-46d5-b274-aaefe626abac.png)

![blur1680730824305.jpg](https://user-images.githubusercontent.com/60188451/230218534-b4cbebc4-1ef0-4b71-b9eb-4cc0156fe09b.jpg)

**Comment by Sn0wfreezeDev** [comment]
You would need at least 3 discoveries to trigger an alert. 2 are not enough for our tracking algorithm to detect a device as a tracker
