### ISSUE TITLE
Incorrect locations shown

### ISSUE THREAD

**Issue by philnagel** [seemoo-lab/AirGuard#127]
I am getting notifications for 2 devices that are following me. I believe these are false positive alerts but what is strange is that the locations shown for both of the devices are identical, and they are both showing incorrect locations.

In this screenshot, only 1 of the pins corresponds to my actual location, I never visited any of the other locations on the days this is reported. I believe these tags are located somewhere at my office, which is very likely since there are a lot of other people here who probably have tags on their keys, etc. I am wondering if the reason it is alerting me is because it is picking up these tags at more than one location, where they are all incorrect except for one? In other words, does the algorithm for determining if something is following me, consider whether it is seen > 1 locations?

![Screenshot_20230426-084758](https://user-images.githubusercontent.com/17130646/234597436-968836f8-c81f-4b8e-82d5-34f9367241a1.png)
(I disabled networks temporarily to block the map tiles from loading for this screenshot)

By the way, I believe the additional locations are just the "coarse" locations from cell towers or similar. I think I have everything set up correctly for the app to be able to use precise locations though.

![Screenshot_20230426-084003](https://user-images.githubusercontent.com/17130646/234597301-70953376-7de6-4e51-8ef0-b724efa7fad3.png)
![Screenshot_20230426-084017](https://user-images.githubusercontent.com/17130646/234597320-6dc146bb-9127-4d5b-8a19-a8cfffa50de7.png)

**Comment by Zoarial94** [comment]
I am seeing a similar issue, but with locations I have been to. Recently I've had at least 2 false positives. 

Today, I left home with no devices that could've been tracking me, drove to 2 different locations, and returned home 7hrs after first leaving. I only received a notification once I returned home. 

The map shows a point at my apartment from before I initially left, a point at my last stop before directly heading home, and a point once I got back home. I can confirm I don't have a tracker in my car or on my person. 

I suspect the app is using a stale location sometimes. 

I am using the latest version on Graphene OS on a Pixel 6 Pro. 

![Screenshot_20230819-224329.png](https://github.com/seemoo-lab/AirGuard/assets/20785870/8ddf0026-2955-426c-a479-8e39279f47f7)

**Comment by Sn0wfreezeDev** [comment]
In the worst case we use older locations. Our algorithm works like this:

1. The app queries a current location over GPS or Wi-Fi
2. If no location is found in 60s we default back to the last location known by Android
3. This location can be older.

We try to use the best possible technique to get the most current location. Depending on the conditions it might not work and we only get an old location.

Kind regards
Alexander Heinrich

**Comment by aereaux** [comment]
This seems to be causing a lot of false positives for me.  It might be made worse by the fact that (I think) my phone (grapheneos) doesn't have a wifi-based location provider.  But when I stay in one location for a while sometimes AirGuard thinks that I've been moving around along with whatever airtags have been near me for that time.  Is there some way I can set it to only use non-stale GPS locations?

**Comment by Sn0wfreezeDev** [comment]
That’s interesting feedback to hear. We already have seen some other issues with Graphene OS, so it could be more common with these Android devices.
When we evaluated Pixel and Samsung devices the GPS location would reach a good accuracy after about 30-40s. So we expected that in most cases this would work when combining it with the network provider for inside environments. However, this seems to be a misconception for some Android versions.

We will look into this further.

Kind regards
Alexander Heinrich

**Comment by aereaux** [comment]
It may also be more prominent with certain locations.  When I'm in my apartment it seems to take a while to get a first fix, probably longer than 60s some or most of the time.

Let me know if there's anything I can do to provide more information or debugging.

**Comment by Sn0wfreezeDev** [comment]
So it seems like GPS may be slow and the network location provider too inaccurate. Both in combination could lead to that issue. In version 2.1 we also rely on the fused location provider and take more time until the location fixes

**Comment by aereaux** [comment]
Unfortunately it seems that it still causes false positives for me with 2.1.
