### ISSUE TITLE
[Enhancement] Offer a way to remove device from Ignored Devices

### ISSUE THREAD

**Issue by lazytownfan** [seemoo-lab/AirGuard#13]
I would like to suggest creating some method for the user to remove a device from the Ignored Devices list.

This is because I've personally accidentally put a detected device onto the Ignored Devices list by accident. Luckily, I was only testing the app out when this happened, so I could reset the app's storage and lost no important app data. However, this would not be a good choice for app users with an extensive and/or long device detection histories.

**Comment by Trup3s** [comment]
This feature is already implemented, but maybe not so intuitive if you don't know it exists. ;)
Just swipe the device from right to left to removed and the other way to rename it. Renaming is also possible in the normal device list.
