### ISSUE TITLE
2.0 hangs indefinitely. Trying to downgrade made it worse

### ISSUE THREAD

**Issue by GsakuL** [seemoo-lab/AirGuard#135]
since the 2.0 update, the app always hangs on the start screen (with the logo). Android even showed the "App not responding" Popup (see below).
I've tried downgrading via FDroid, but the installation failed, version stayed 2.0. But now the App doesn't even show the logo anymore and stays black.
I've tried the GitHub Build, which is a different package id, so i can install it in parallel. It starts normally, but obviously has no data.

Installed via FDroid. Stock Android 13 (build TQ3A.230605.010), Pixel 6.

![grafik](https://github.com/seemoo-lab/AirGuard/assets/6844160/12450fff-c234-4297-902e-44042398c757)

**Comment by Sn0wfreezeDev** [comment]
Maybe try version 2.1 now 😉
