### ISSUE TITLE
App won't open (and work?)

### ISSUE THREAD

**Issue by stormjk2** [seemoo-lab/AirGuard#138]
Hi,
I am having a problem with the app on Lineage 19.1 (Android 12) on a Sony XA2 Ultra.
After installation the setup guide from the app works like a charm with enabling access to bluetooth etc. But after the last prompt (and pressing the arrow further) the app closes without any error message. Trying to reopen it then fails similarily, no error message.
When looking which app accessed my location last, I see AirGuard in the list. So I don't really know whether the app is doing something in the background or not.
I tryed deleting app-data and cache and reinstalling it. The problem mentioned above still persists.
Please tell me which information to provide to help you get into it (if you would). 
Thanks

**Comment by onlyJakob** [comment]
Same here, in my case related to  #131.

#133 fixes that, a bugfix release would be nice.

**Comment by stormjk2** [comment]
@onlyJakob thanks for your reply and yes, a bugfix release would be very nice. I think a lot F-Droid users (that is where I downloaded the app) are on custom roms without gapps and would benefit from that.

**Comment by retroluv** [comment]
Same issue since v2 on A13, but If I disable location on my phone, AirGuard wont crash.

**Comment by Sn0wfreezeDev** [comment]
I think that issue was related to this issue https://github.com/seemoo-lab/AirGuard/issues/148. That should be fixed in version 2.1
