### ISSUE TITLE
Click on the [x] button does not remove the study participation notification

### ISSUE THREAD

**Issue by niccokunzmann** [seemoo-lab/AirGuard#143]
I just had an Android notification open to ask me to participate in a study. When I clicked on it, I came to the main tab. When I clicked on "participate", then the button did nothing #136. When I clicked on the [x] button, I expected the notification on the main tab to go away. It did not go away.

**Comment by treysis** [comment]
I have the same issue. I don't want to see the study participation tile anymore. But the "X" to click it away does nothing. It's been bugging me for weeks but finally I wanted to open an issue just to see that @niccokunzmann already did.

**Comment by Sn0wfreezeDev** [comment]
That's now finally fixed in 2.1, sorry for that issue.
