### ISSUE TITLE
rename device

### ISSUE THREAD

**Issue by cammas** [seemoo-lab/AirGuard#144]
Hello thank you for the app, I've had it installed for a while.

- is it possible to suppress all survey messages I know it's important but sometimes it's annoying

- more importantly is it possible to rename a device ???

this would be very useful to eliminate known devices and other uses thank you

**Comment by Sn0wfreezeDev** [comment]
Hi,

Yes you can rename devices by swiping over the entry.

Kind regards,
Alexander Heinrich

**Comment by cammas** [comment]
thank you for the reply, I guess it's possible to rename tracking device. but not those in the scan tab that are around

**Comment by Sn0wfreezeDev** [comment]
Yes that’s right.

In the scan tab, you cannot rename them.

Kind regards,
Alexander Heinrich
