### ISSUE TITLE
Add support for Kisha Umbrella beacons

### ISSUE THREAD

**Issue by DominikNovosel** [seemoo-lab/AirGuard#146]
https://www.getkisha.com/product/6x-kisha-smart-tracker/

Kisha umbrellas are a common corporate gift and the Bluetooth beacon can be repurposed as a tracker. Additionally, the stock companion app is barely functional on modern devices. AirGuard might be an adequate replacement, even without modification, despite this not being its intended purpose.

**Comment by Sn0wfreezeDev** [comment]
I don't think these beacons have a wide coverage and as far as I understand they are just used to show you when you left your umbrella at some place, but they do not offer a tracking network.
