### ISSUE TITLE
Clarification: Bluetooth on or off?

### ISSUE THREAD

**Issue by famo** [seemoo-lab/AirGuard#15]
Neither in the app itself nor on the website I found any instructions regarding the bluetooth settings for the device.
I see two possibilities:

1. bluetooth off: bluetooth can be set to off and AirGuard will (somehow) briefly enable it for the periodic scans.
2. bluetooth on: bluetooth has to be set to always on.

Which on is it?

**Comment by Trup3s** [comment]
It's the second one.

However, we should inform the user that if Bluetooth is turned off, the app cannot scan.
