### ISSUE TITLE
Migrate gradle script to Kotlin DSL

### ISSUE THREAD

**Issue by Jean-BaptisteC** [seemoo-lab/AirGuard#153]
I can doing migration to Kotlin DSL.
Actually Kotlin DSL is more slow then Groovy but it's planned to increase build performance.
https://developer.android.com/build/migrate-to-kotlin-dsl

**Comment by Sn0wfreezeDev** [comment]
As long as these will be slower than the working solution we have now, I would not do the migration. 
Usually migrations in Android Studio trigger a lot of necessary adaptions and bugs, that I would like to avoid. 
If there is a security-wise reason to use Kotlin DSL that might make sense.

**Comment by Jean-BaptisteC** [comment]
Ok I understand your position
Build time has been improved with Gradle 8.3 and 8.4
