### ISSUE TITLE
Feature Request: Allow naming of known devices.

### ISSUE THREAD

**Issue by GlennGoddard** [seemoo-lab/AirGuard#156]
Use case would be to help locate your own devices.  If named, then the MAC would be replaced with a user defined name when displaying the scanned devices.

**Comment by Sn0wfreezeDev** [comment]
You can name known devices, just swipe left on table. 
It will only keep the name for trackers that do not change the MAC address, like Tile

**Comment by zachberger** [comment]
I wonder if any changes could be made to make this more discoverable?
