### ISSUE TITLE
Optionally include logging of generic Bluetooth devices in addition to known tracker types

### ISSUE THREAD

**Issue by forever-and-a-day** [seemoo-lab/AirGuard#158]
This can be useful for detecting if you're being tracked by any kind of phone/Bluetooth-enabled device, or just for more detailed insights on the devices you encounter.

**Comment by Sn0wfreezeDev** [comment]
We focus on trackers and therefore only detect these devices. General logging could lead to issues where people are feeling tracked by headphones, smartphones and smartwatches around them.
