### ISSUE TITLE
Playing sound on Tile trackers

### ISSUE THREAD

**Issue by TheCheshireMan** [seemoo-lab/AirGuard#163]
This is the only app that I've found that lets me properly scan for trackers without giving up data. Thank you for your important work on it.

I currently own two Tile Pro (2020 and 2022 versions). Would it be possible to add the functionality to make the Tile play a sound, in order to be able to find where exactly they are? This would have the added benefit of avoiding needing the proprietary app in order to use one of the most important functionality of Tile trackers.

I'm quite good at tinkering and completely willing to collaborate on developing the functionality, if it helps.

**Comment by Sn0wfreezeDev** [comment]
Hey there, 
We tried to reverse-engineer this and discovered that Tile blocks the ability to play sound for anyone who is not the owner. 
So unfortunately we cannot add this feature to the app
