### ISSUE TITLE
Including in scanning also unknown devices (not Apple and DIY ones)

### ISSUE THREAD

**Issue by serrq** [seemoo-lab/AirGuard#165]
I wish detecting any kind of bluetooth device, also not Apple or not airtags, like unknown and/or non-compliant devices, or different OS.

![1000108040](https://github.com/seemoo-lab/AirGuard/assets/113377431/4ea7eeaf-7641-4db1-9fba-506e0790ba25)

**Comment by Sn0wfreezeDev** [comment]
We already detect other devices. These are masking as "Apple Devices" but could be a manipulated tracker that tries to evade tracking detection. 

There is no tracker that uses ZigBee or other 2.4GHz based frequencies. These trackers require other devices to find them so it is necessary to use a common technology like Bluetooth.
