### ISSUE TITLE
Make the donation process easier (to support development)

### ISSUE THREAD

**Issue by serrq** [seemoo-lab/AirGuard#166]
Please add direct cryptocurrency addresses within the app. All offline. Easy tap and donate without leaving the app: I don't want going around to websites. I don't want support FIAT economy.

TRX, AVAX, LTC, BTC, XEC, BNB, SOL, BCH, ALGO, XTZ, HBAR, DASH, FTM, XRP, XDC, ADA, XLM, KAS, XMR, SEI, INJ, SUI addresses available for donations (addresses have to be copyable).

Here an integration example made by other developers.

![1000092943](https://github.com/AdamGuidarini/MediTrak/assets/113377431/528e3065-97e2-4851-a590-ecaece5e2727)

**Comment by Sn0wfreezeDev** [comment]
We do not accept donations
