### ISSUE TITLE
v2.3 crashes instantly after set up

### ISSUE THREAD

**Issue by 825i** [seemoo-lab/AirGuard#182]
I can't open the app even for a second after finishing set up and giving all requested permissions. Please see the video. I have tried clearing the cache.

Xperia 1 V
Android 14

https://github.com/user-attachments/assets/28ea6ed8-8508-45b8-a22f-f18801f4b020

**Comment by antimatter84** [comment]
I observe the same issue. I have just updated to version 2.3 an the app crashes immediately on start.

Google Pixel 3a
Android 13

**Comment by nixigaj** [comment]
Same here, Lineage OS 21, Android 14, Sony Xperia 1 II

**Comment by Sn0wfreezeDev** [comment]
This is a duplicate of: https://github.com/seemoo-lab/AirGuard/issues/180 
Please update to 2.3.1

**Comment by Sn0wfreezeDev** [comment]
F-Droid has its own update mechanism. We don't know how long it will take for them to publish our new version.
