### ISSUE TITLE
Suggestion: Renaming devices

### ISSUE THREAD

**Issue by da-stoi** [seemoo-lab/AirGuard#2]
This app was able to find and alert me of one of the DIY AirTags I made with OpenHaystack when a regular iPhone couldn't. Really cool stuff!

That being said, I had to add the device to my ignored devices list. The mac address really helped to confirm it was really my DIY AirTag, but I thought it might be super helpful to be able to rename the AirTags you add to your ignore list, or just rename them in general. For example I don't necessarily need to add my friend's real AirTags to the ignore list, but if I was able to rename them and I got an alert, it would help me figure out if I should be worried or not.

Keep up the great work!

**Comment by Trup3s** [comment]
Thanks for your Feedback!

I already had the function to rename devices in mind, but I haven't had the time to implement it yet. Should not be too much effort and maybe I find time in the next few weeks to implement!
