### ISSUE TITLE
Some recolorings in Material 3

### ISSUE THREAD

**Issue by turtlegarden** [seemoo-lab/AirGuard#22]
# Status Bar
## Description
The latest version of AirGuard is showing the primary Material 3 color in the status bar- which is often light and has low contrast with the white foreground.
## Reproduction
- Have an Android 12L beta phone
- Open AirGuard
- See bug
## Screenshot
![Screenshot_20211223-091053](https://user-images.githubusercontent.com/52264162/147266164-46b7fb7d-75e6-4413-b43b-d1ee115852e6.png)
## Proposed Fix
Make the status bar the same color as the background of the main app UI.
# SVG color issues
## Description
The latest version of AirGuard shows SVGs that don't align with Material 3 dynamic color.
## Reproduction
- Have AirGuard on Android 12
- Run manual scan
- See undesired behavior
## Screenshot
![Screenshot_20211223-122058](https://user-images.githubusercontent.com/52264162/147283932-af404e1c-6b56-47de-967d-1bf3c02f2a5b.png)

## Thanks for looking into this issue!

**Comment by foreverxml** [comment]
Thanks @Trup3s for fixing the status bar issue. :)
