### ISSUE TITLE
Display copyright on map view

### ISSUE THREAD

**Issue by guerda** [seemoo-lab/AirGuard#24]
The current version from F-Droid is missing a copyright notice from OpenStreetMap. OsmDroid does not seem to display it by default, so a custom one needs to be added.
Here's one option which might work:

`//Copyright overlay
mCopyrightOverlay = new CopyrightOverlay(context);
mMapView.getOverlays().add(this.mCopyrightOverlay);
`

https://stackoverflow.com/a/50968755/32043

The text "© OpenStreetMap contributors" is required by the license. 
See https://openstreetmap.org/copyright

https://mobile.twitter.com/OSM_Pontarlier/status/1444744213330022403

**Comment by Trup3s** [comment]
Thanks for making us aware of this! I will add this to the next version!
