### ISSUE TITLE
Can't turn off "use location"

### ISSUE THREAD

**Issue by morta5** [seemoo-lab/AirGuard#25]
After turning off "use location" in the AirGuard settings and reopening the app or making a manual scan, the setting gets automatically turned back on.
Here's a screen recording: https://cloud.hakimy.tk/s/x7Aondq6qXSJyDw

**Comment by Trup3s** [comment]
Interesting behavior! I will look into this!

**Comment by Sidahmed-ben** [comment]
hello @Trup3s , I'm interested by the issue, i can find a solution for this , do you agree that i contribute in the project . Thank you
