### ISSUE TITLE
Android 7.0 version?

### ISSUE THREAD

**Issue by TrainzLuvr** [seemoo-lab/AirGuard#27]
Hi,

Where can I get an Android 7.0 version, the releases all appear to be for 8.0?

TIA.

**Comment by Sn0wfreezeDev** [comment]
Currently we only support Android 8.0 due to API limitations. 
We are looking forward to extend the support to Android 5.5

**Comment by Trup3s** [comment]
AirGuard 1.1.0 now has a minimum SDK level of 21. That means all Android versions down to Android 5.0 are now supported!

**Comment by arkon** [comment]
I noticed that the project no longer builds properly since the `ScanResult#isConnectable` method only works in SDK 26+, but the AirTag detection seems to depends on that. Is that an issue?
