### ISSUE TITLE
Text is cut off

### ISSUE THREAD

**Issue by Ein-Tim** [seemoo-lab/AirGuard#28]
The text defined in 
https://github.com/seemoo-lab/AirGuard/blob/bdbf32f64dd2a49dfe5f9ea58e1f12fcaf6fcdef/app/src/main/res/values-de/strings.xml#L136 is cut off on my Huawei P Smart 2019 with Android 10 and the latest version of AirGuard (from Google Play Store) installed:

<img src="https://user-images.githubusercontent.com/67682506/148291644-88865cfe-a24e-49b3-890b-9a3daa06da23.jpg" width="300">

**Comment by Sn0wfreezeDev** [comment]
Thanks for the report @Ein-Tim

**Comment by Ein-Tim** [comment]
Closing as this issue was fixed.
