### ISSUE TITLE
Cannot play sound when testing on the newly bound AirTag

### ISSUE THREAD

**Issue by dylanxu054** [seemoo-lab/AirGuard#3]
The AirTag that I bound before can play sound. After I rebind it, the sound will be invalid.

**Comment by dylanxu054** [comment]
I tried it again later, and the sound can be played, but it doesn't seem to be stable.

**Comment by Sn0wfreezeDev** [comment]
Yes it's not stable. The AirTag kills connections very quickly and when the connection setup takes a bit longer it might not succeed.
