### ISSUE TITLE
Unknown devices

### ISSUE THREAD

**Issue by Citro12** [seemoo-lab/AirGuard#43]
Hello, the app finds devices with different mac addresses every 15 minutes on the map and in the manual scan, but in the same place.  Possibly mac books.  What devices could that be?  If there are no trackers, can you exclude them from the search?

**Comment by Sn0wfreezeDev** [comment]
Hi, 
Yes most likely those devices are not trackers. But we do not exclude them, because it is possible to build self-made trackers that copy the behaviour of MacBooks and work just as good. So we want to keep them in the app

**Comment by Citro12** [comment]
Hello,
Are there other trackers besides Apple Macbooks in the MyFind network?

**Comment by Sn0wfreezeDev** [comment]
AirTags, Chipolo Tags, Self-Made Tags using our OpenHaystack project: https://github.com/seemoo-lab/openhaystack

**Comment by Citro12** [comment]
Thanks

**Comment by Citro12** [comment]
one more question, normal iphone devices are recognized, not just mac books.  Would be interesting to know why?
