### ISSUE TITLE
Add detection of Tile trackers

### ISSUE THREAD

**Issue by AndreasTuranski** [seemoo-lab/AirGuard#45]
Having both AirTag and Tile Tracker detection in one app would be useful, likely reuse significant portions of the code base, and provide energy efficiency vs having another app price anti-tracking for Tiles and do its own BLE scans.

**Comment by EvanCarroll** [comment]
I came here to suggest the same thing.

**Comment by createcandle** [comment]
I've just created a Python bluetooth scanner to do the same thing. It reports both Airtags, Tiles and bluetooth beacons (although I haven't verified that last one).

https://github.com/createcandle/bluetoothpairing/blob/main/scanner.py

The Tile in my vicinity (I don't own one, but apparently a neighbour does) doesn't seem to emit advertising bytes, but it does emit a name: 'Tile'. So the code just looks for that instead.

**Comment by Sn0wfreezeDev** [comment]
We are looking into that topic at the moment. There will be a release covering this in the next weeks using a simple approach at first

**Comment by Myzel394** [comment]
My tiles are detected properly. @AndreasTuranski can you confirm this? If yes, we can probably close this issue

**Comment by jezzaaa** [comment]
My Tiles are detected also, which is awesome. As well as an extra one in bit familiar with. But I can't tell which ones are mine and which one isn't. The UI instructions to handle/ignore my Tiles don't work. I can't identify my MAC addresses in the Tile app.

**Comment by Sn0wfreezeDev** [comment]
We will check why ignoring the Tiles does not work. Thanks for checking. 
Currently, we have not identified if we can let the Tiles ring like an AirTag. Therefore, it's not possible to directly identify them this way. Maybe the `adb logs`  can show you its MAC address?
