### ISSUE TITLE
Enhancement: button to trigger manual scanning

### ISSUE THREAD

**Issue by pellaeon** [seemoo-lab/AirGuard#5]
Currently, it seems the app only scan [every 15 minutes](https://github.com/seemoo-lab/AirGuard/blob/main/app/src/main/java/de/seemoo/at_tracking_detection/worker/WorkerConstants.kt#L4) or so?

I know Android limits the minimum PeriodicWork interval to be [15 minutes](
https://developer.android.com/reference/androidx/work/PeriodicWorkRequest). But is it possible to add a button to manually trigger a scan?

**Comment by Sn0wfreezeDev** [comment]
Thank you for the addition. We'll add this to the list of features for the next update.

**Comment by Trup3s** [comment]
Ability to trigger a manual scan was introduced in version 1.0.6!
