### ISSUE TITLE
Stuck inside "Tracker Detected"-list

### ISSUE THREAD

**Issue by DrMaxNix** [seemoo-lab/AirGuard#53]
When viewing Tracker-lists there is no way to get back to dashboard using the UI (hardware back-key works tho).

**Steps to reproduce:**
1. Open AirGuard (start-page / dashboard should show up)
2. Click on first box which whows current risk level
3. Click on "Trackers detected" or "Locations tracked" box in top (needs to have detected devices) or click on "Other devices found" box in scond row
4. Notice that there is no back-btn in UI
5. Notice that nav-menu on bottom highlights "Ignored" even tho we are comming from dashboard
6. Click on "Dashboard" in nav-menu on bottom and notice that it does nothing
7. Click on "Ignored" or "Settings" in nav-menu on bottom and then click "Dashboard" in nav-menu on bottom again and notice that "Tracker Detected"-list is still showing

_AirGuard version: 1.2 (f-droid) on Android 12_

**Comment by Trup3s** [comment]
The problem is probably that we are reusing the device list for both views, but that doesn't quite work with the navigation logic. Maybe in the next week i'll find some time to tackle this and get it ready for the next update.
