### ISSUE TITLE
[Question] What does the 'last scan' entry mean?

### ISSUE THREAD

**Issue by EnerGeh** [seemoo-lab/AirGuard#54]
I very appreciate your app, thanks for the possibility to get notified about possible tracking devices.
What I don't understand is the 'last scan' section on the status screen, what does that mean? My 'last scan' is often some hours ago, in worst cases some days.
I did exclude the app from battery saving and use a phone without google services (microG installed, but only partly activated).

**Comment by Trup3s** [comment]
That's really interesting!  Which app and android version are you running and can you confirm that all necessary permissions are given?

**Comment by EnerGeh** [comment]
I'm usingan AOSP based Android 10 with following APP Version: 
![Screenshot_20220319-201213_SHIFT_Home](https://user-images.githubusercontent.com/28715981/159135246-7cb8e88c-8d2e-4111-9500-f2d572622ee5.png)

**Comment by HW-Chris** [comment]
Hello Dev-Team,
thank you very much for this great App!
Can you explain the background scanning interval (or trigger to scan) please?
On both of my phones (Google Pixel 3a using Android 12 stock rom & Nexus 5 using LineageOS 14.1) there was no scan activity within more than 12 hours using app version 1.3.2. In a previous version (<= 1.2, i don't know exactly) my Pixel 3a found more than 40 devices (some AirTags but mostly iPhones) within 7 days. Using version 1.3.2 no device was found in the same areas (home & office).
Maybe background scanning is still broken in version 1.3.2?

First screeshot: Pixel 3a, 2nd: Nexus 5:
![Screenshot_20220403-114853](https://user-images.githubusercontent.com/102901079/161422663-15013931-c66d-4775-b142-d21a784aab37.png)
![Screenshot_20220403-114821](https://user-images.githubusercontent.com/102901079/161422670-638ff1a5-08b9-4c3e-893d-49df2340c9d2.png)

**Comment by EnerGeh** [comment]
This issue was fixed in 1.3.4. Thank you very mich.

**Comment by Sn0wfreezeDev** [comment]
Thanks everyone for reporting this!
