### ISSUE TITLE
[Enhancement] Status bar not visible in light mode & navigation bar black.

### ISSUE THREAD

**Issue by n1snt** [seemoo-lab/AirGuard#57]
Currently, the status bar shows no icons in light mode & the navigation bar is not colored which looks something like this:<br>
<p align="center">
<img src="https://user-images.githubusercontent.com/46300244/159776829-8351933e-168c-43e3-83cb-b20ac0fee2ee.jpg" width="30%">  
</p>
I have made a pull request #55 to fix both of these issues & now it looks something like this:<br><br>
<p align="center">
<img src="https://user-images.githubusercontent.com/46300244/159776861-51070e63-13e3-4d8e-80ad-65bf35dc3065.jpg" width="30%">
</p>

**Comment by n1snt** [comment]
Hey, @Sn0wfreezeDev please let me know if there are any issues with my PR.

**Comment by Sn0wfreezeDev** [comment]
Fixed, thanks @n1snt for the PR
