### ISSUE TITLE
[Bug] Automatic background scan is not working

### ISSUE THREAD

**Issue by Sorunome** [seemoo-lab/AirGuard#63]
Despite having the app excempted from battery optimization, the background scan is not working. Every time when opening it the "Last scan" field is from I have last opened the app.

I use LineageOS 18.1 (Android 11) and would be happy to provide any debugging information (adb logcat, whatnot) as needed

**Comment by lenhart** [comment]
Issue #54 seems to be related.

I have the same problem with an old Android 9 Phone (Moto X4). The last scan is some old date 14 days past (even when I just did a manual scan) and it definitely did not detect an Airtag on a borrowed bike which I used for a couple of hours..

**Comment by aramova** [comment]
Also running into this as if the latest version 1.3.3 look Android 12

**Comment by Sn0wfreezeDev** [comment]
Hi, 
We believe that this issue might be related to Android updates. We have delivered several updates in the recent past, and it looks like an update might stop the Android background worker. According to the documentation, this should not happen, but we will add several changes that will reschedule the background scans after the app was updated.

**Comment by Sn0wfreezeDev** [comment]
Should be fixed by version 1.3.4: 
https://github.com/seemoo-lab/AirGuard/releases/tag/1.3.4 

It'll be available on Google Play a bit later, since we use a phased rollout

**Comment by Sorunome** [comment]
Yes, seems to be fixed now, thanks a lot!
