### ISSUE TITLE
Location bug on Pixel 5?

### ISSUE THREAD

**Issue by mmueller** [seemoo-lab/AirGuard#65]
I left home today at 10:15. I got notified of several trackers today, and when I look at the timestamps and the locations of the pings, there are pings at my home at 11:00, 11:05, 11:20 mixed in with pings at my actual location (not home) at 11:15, 11:32. I don't own any trackers, but I'm probably near some in town right now. I've been in the same spot for the last two hours.

Is this a bug with location services on Android? If my phone gave AirGuard locations in different places while I sat near the same air tag, I can easily imagine it generating false positives as if that tracker was following me. Is this a known issue on Pixel phones, or maybe just me? Is there any way for AirGuard to know when it's getting a "stale" location from the system, or is that not really a thing?

In settings, AirGuard has location permission "all the time" and "use precise location" is enabled. The global "Google Location Accuracy" (aka "Improve Location Accuracy") is also enabled, but I wonder if this can actually introduce errors? I just dug into the developer options to see if a mock location app is configured, and no, there isn't one.

**Comment by larsdennert** [comment]
I have an issue where air guard rarely records location when it gets a hit. Almost all tags don't have location data. No permissions have been denied.

**Comment by Sn0wfreezeDev** [comment]
Should be fixed in the next update
