### ISSUE TITLE
[Suggestion] Add ability to "whitelist" devices. 

### ISSUE THREAD

**Issue by SteadyStatus21** [seemoo-lab/AirGuard#74]
You should be able to whitelist devices, so that the app will not warn you every time you enter it. For example, I own a tile, and I keep it in my wallet, and even though I've muted it, the app shows that I am unsafe.

Thanks,
SteadyStatus21

**Comment by Sorunome** [comment]
same as #71?

**Comment by SteadyStatus21** [comment]
Yup! Thank you!
