### ISSUE TITLE
[Bug] Map background not showing

### ISSUE THREAD

**Issue by BigweldIndustries** [seemoo-lab/AirGuard#75]
![IMG_20220518_174033](https://user-images.githubusercontent.com/75338791/169160463-326121ae-d384-4c06-b6aa-0d2f5302e7f6.jpg)
The background here is supposed to show the location the tracker traveled. Without this I can't tell whether or not its a false alarm. This is in my normal profile without trackercontrol. Anyone else experience this?

Pixel 5a, Android 12 (Calyx)

**Comment by Sorunome** [comment]
I have this, too, however only if I tap on the notification. If I start the app normally, and then go to the list of tracked devices it does show for me

**Comment by BigweldIndustries** [comment]
> I have this, too, however only if I tap on the notification. If I start the app normally, and then go to the list of tracked devices it does show for me

i just checked, this seems accurate to me as well

**Comment by MrRulf** [comment]
Having this too, but the fix doesn't work, FP4 Lineage 20

**Comment by MrRulf** [comment]
I don't know why, a day later it works...

**Comment by Sn0wfreezeDev** [comment]
It’s an issue with the OpenStreetMaps integration in Android. It’s not very stable, but since we want to be privacy sensitive we cannot use Google Maps.


Kind regards,
Alexander Heinrich
