### ISSUE TITLE
Add ability to give a device a friendly label

### ISSUE THREAD

**Issue by ZeroChaos-** [seemoo-lab/AirGuard#77]
Some devices move with me but are known.  Examples may include a tag owned by myself or a known trusted associate.  I would rather label those devices instead of just ignoring them, so I can remember why they are ignored.

Great software by the way, thanks for all your hard work.

**Comment by Sn0wfreezeDev** [comment]
Good point, which kind of tracker is this? An AirTag or a Tile. 
The issue is that AirTags is not identifiable after 24 hours. They are changing their MAC address around 4 a.m. Therefore, we cannot link them back to the old device with 100% certainty.

**Comment by Sn0wfreezeDev** [comment]
You can rename the tags by swiping them in the list. Then you can name it My Tile for now.

**Comment by ZeroChaos-** [comment]
Thanks! That may be all I really needed.  Feel free to close if you don't have additional better idea for this request.
