### ISSUE TITLE
Suggestion: Dashboard / Devices page sorting

### ISSUE THREAD

**Issue by jakub-studio** [seemoo-lab/AirGuard#8]
Hi there,

First of all, I think this is an absolutely incredible project in terms of personal safety. I do have one suggestion from a UX perspective:

I think that sorting should be added to the Dashboard / Devices page (e.g. sort by beacon count, first / last seen, serial number or assigned name).

This can make it easier to find particular FindMy devices.

Thank you

**Comment by Sn0wfreezeDev** [comment]
Yes we will be definitely adding filters and sorting abilities in those sections.
