### ISSUE TITLE
Why does AirGuard require internet access?

### ISSUE THREAD

**Issue by marek22k** [seemoo-lab/AirGuard#80]
Hello,

I use the Datura Firewall and my smartphone and it shows that AirGuard is allowed to access the Internet by default. Why is this?

I have disabled internet access for AirGuard and it still works.
![Screenshot_20220701-130741_1](https://user-images.githubusercontent.com/46723399/176883493-86d57912-ce54-4ab3-8878-35cd38d285cd.png)

**Comment by Ryu945** [comment]
There is optional data sent back for the point of the research study.  I would prefer if by default it wasn't given internet access unless the option to participate in the study was turned on.   Sort of like asking for a phone permission.

**Comment by Sn0wfreezeDev** [comment]
Also the map needs internet 😊 But you are welcome to disable it

**Comment by Sn0wfreezeDev** [comment]
We use OpenStreet Maps, it requires internet access. Also the app allows you to send research data. 
The permission is not dangerous. Many other permissions are considered as dangerous but this one is not.
