### ISSUE TITLE
Button not fully visible

### ISSUE THREAD

**Issue by JonnyTech** [seemoo-lab/AirGuard#85]
Button at bottom of panel not fully visible and page not scrollable

![Screenshot_20220806-175757](https://user-images.githubusercontent.com/3584732/183258766-035cc431-2181-4d8b-887a-4a79c669ce95.png)

**Comment by Smarshal21** [comment]
i have fixed this issue
@Sn0wfreezeDev  ptal  - https://github.com/seemoo-lab/AirGuard/pull/139
