### ISSUE TITLE
[Bug] Cannot ignore device

### ISSUE THREAD

**Issue by aytimothy** [seemoo-lab/AirGuard#92]
Um, where's the ignore device button?

Is it the "mark as false positive" button? It seems to forget that mark as soon as I exit the individual result screen.

**Comment by larsdennert** [comment]
Only works for tile devices that don't randomize their Mac address

**Comment by aytimothy** [comment]
Um, this happened with an AirTag, so I guess AirTags do randomize their MAC addresses...

**Comment by Stebalien** [comment]
I'm seeing the same thing:

1. Click on the suspected tracker.
2. Check "false alarm".
3. Click back.
4. See that one tracker is still reported as "detected" in the "Risk evaluation" page.
5. Click on the device again.
6. "False alarm" is unchecked.
7. Navigate to "Devices", there are no "ignored devices".
8. Navigate to the dashboard, it says "no risk"/no trackers found? So maybe something is working-ish?

**Comment by Sn0wfreezeDev** [comment]
@Stebalien 
Thanks for reporting this with the steps to reproduce. We will have a look at it.

**Comment by Stebalien** [comment]
Thanks!
