### ISSUE TITLE
Apple devices

### ISSUE THREAD

**Issue by Citro12** [seemoo-lab/AirGuard#93]
[Question] why are all iphones (Apple devices) etc. found, are they only devices that are connected to an ipod or airtag or only have the myfind network activated?  Not all iphones are found in the search.  A question of understanding

**Comment by larsdennert** [comment]
Any apple device could be used to track someone. It doesn't have to be an airtag. If the Mac address falls in the apple range it is queried is my guess. Airtags and earpods are separated out.

**Comment by Citro12** [comment]
Not all Apple devices are displayed in my area, why? Or those that had an Airtag or Airpod connected ?

**Comment by Sn0wfreezeDev** [comment]
It's possible to create an AirTag like tracker that imitates an Apple device. These trackers can hide from Apple's tracking detection. We also check for them to make sure you are not tracked
