### ISSUE TITLE
Location data always "not available"

### ISSUE THREAD

**Issue by lbdroid** [seemoo-lab/AirGuard#94]
Background:
Pixel 6 Pro running GrapheneOS, withOUT google services.

Rationale:
Objective is to maximize privacy by decreasing the ability for anyone/anything to track the device, including google. This is very much consistent with the purpose of AirGuard, to find things that may be tracking you so you can disable them.

Issue:
Without google services, network/celltower based approximate location is entirely unavailable, which means that GPS is the only option for determining the device's position.

GPS takes a while to lock on. If depending on a GPS fix, enough time has to be provided in order for it to work most of the time, at least when conditions permit.

Pixel 6 Pro typically takes around 15-20 seconds. It could take more if conditions are challenging. AirGuard appears to time out the location request at 8 seconds, which is just not enough time for a GPS lock on most devices unless its already warm or locked.

Solution: Increase GPS timeout to substantially higher value, such as 1 minute, which is probably high enough most of the time for most devices when outside but in a pocket, and likely not the end of the world if indoors where signal is just not good enough.

https://github.com/seemoo-lab/AirGuard/blob/main/app/src/main/java/de/seemoo/at_tracking_detection/detection/ScanBluetoothWorker.kt#L252

**Comment by Sn0wfreezeDev** [comment]
An Update fixing this is coming soon.
