### ISSUE TITLE
Add support for detection of other tracker brands, eg. Samsung Smart Tags

### ISSUE THREAD

**Issue by DominikNovosel** [seemoo-lab/AirGuard#95]
Sub $50 tracking devices are rapidly increasing in availability and popularity, and technologies such as AirGuard are very important for counteracting malicious usage of such devices and preserving people's personal safety. That being said, supporting detection of more tracker brands is a significant long-term concern. To this end, I would like to ask the following: Are there any special considerations when it comes to the viability of adding support for a given piece of hardware?

For example:
- prerequisites that the hardware itself should fulfill, such as the principle of operation and underlying technology
- whether physical access to the device is required for the purposes of reverse-engineering
- whether the manufacturer is likely to object to the interaction of their hardware with 3rd-party software
- if it's necessary to reverse engineer the communication protocol on a per-device basis, how viable is it to collaborate on implementation with owners of the relevant device who do not possess significant programming skills
- general interest in AirGuard's continued development

I specifically mentioned Samsung Smart Tags in the title because that's the hardware I have on hand and am able to test for.

**Comment by lbdroid** [comment]
This is actually trivial to implement. There is no reason at all to focus on specific tracking device brands. Just scan for ANY bluetooth devices that are detectable, and store identifying details. If the same device is detected in multiple locations, then its following you, which makes it a potential tracker.

**Comment by lbdroid** [comment]
Actually, it will work perfectly. Unless something is actually FOLLOWING you (from place to place), then it won't trigger an alarm. How many bluetooth devices do you CARRY that emit periodic beacons? Likely few enough to count on one hand. Most bluetooth devices do NOT emit periodic beacons.

**Comment by DominikNovosel** [comment]
Then I guess my particular case is really weird. The people on my commute route have an unusual propensity for leaving their Bluetooth speakers and stuff in pairing mode.

**Comment by lbdroid** [comment]
How do you know that those aren't trackers?

**Comment by DominikNovosel** [comment]
Most of their IDs contain names of audio equipment manufacturers and are identified as audio devices. Are they trackers in disguise? Maybe. Is it that easy to make a tracker that looks like an audio device? I don't know. Is anyone in my country likely to go through the trouble of doing that? Almost certainly not.

**Comment by lbdroid** [comment]
Almost certainly YES. Programmable bluetooth MCU's like Nordic nRF52840 are cheap and plentiful and *very* easy to work with, and can be made to look like anything you like.

**Comment by DominikNovosel** [comment]
Oof. Welp, there was this one time another passenger paired and blasted a sine wave full volume through one of them, so at least one of them was an actual speaker. In any case, I'm personally not super worried about this since my country is relatively safe, but I cannot speak for everyone else. The devs were running a study about how worried people even were about being tracked a while ago, but I can't seem to track down the results.

**Comment by Sn0wfreezeDev** [comment]
We integrated SmartTags from Samsung. It will be shipped with the next update.

**Comment by DominikNovosel** [comment]
Any estimate for when this update will be released?

**Comment by eelcohn** [comment]
Any update on when the version which supports SmartTags is going to be released?

**Comment by DominikNovosel** [comment]
> Any update on when the version which supports SmartTags is going to be released?

It's released already.
