### ISSUE TITLE
Automatically enable / disable Bluetooth to scan devices 

### ISSUE THREAD

**Issue by Sweazou** [seemoo-lab/AirGuard#99]
As I know, if the Bluetooth isn't enable, the app won't scan for devices, it'd be nice that the app automatically enable Bluetooth to scan devices if it isn't on and then turn it off after if it was off.
Idk maybe I'm crazy because nobody is talking about it.

**Comment by ASerbinski** [comment]
What would be the advantage of turning bluetooth off? Energy savings?

**Comment by Sweazou** [comment]
> What would be the advantage of turning bluetooth off? Energy savings?

It'd but in my case my Bluetooth is always off when I'm not using it

**Comment by Sweazou** [comment]
Security issues

**Comment by Sweazou** [comment]
Security issues

**Comment by ASerbinski** [comment]
Well this is an Android application, so it runs on an Android phone, which unlike those made by the fruit company, does NOT continually spew bluetooth beacons for the whole world to track. I think you might be overestimating the security risk associated with keeping bluetooth turned on.

**Comment by Sweazou** [comment]
I'm talking as an attacker

**Comment by Sn0wfreezeDev** [comment]
There's an API which would allow the app to turn on Bluetooth, but the documentation states that it should only be used to enable Bluetooth on purpose. So we could not use that for background scanning. 

Might be an option to put a setting in the app: activate Bluetooth when doing background scanning.
